export enum ReclineSay {
  TASK = "task",
  ERROR = "error",
  API_REQ_STARTED = "api_req_started",
  API_REQ_FINISHED = "api_req_finished",
  TEXT = "text",
  COMPLETION_RESULT = "completion_result",
  USER_FEEDBACK = "user_feedback",
  USER_FEEDBACK_DIFF = "user_feedback_diff",
  API_REQ_RETRIED = "api_req_retried",
  COMMAND = "command",
  COMMAND_OUTPUT = "command_output",
  TOOL = "tool",
  SHELL_INTEGRATION_WARNING = "shell_integration_warning",
  BROWSER_ACTION_LAUNCH = "browser_action_launch",
  BROWSER_ACTION = "browser_action",
  BROWSER_ACTION_RESULT = "browser_action_result",
  MCP_SERVER_REQUEST_STARTED = "mcp_server_request_started",
  MCP_SERVER_RESPONSE = "mcp_server_response",
  USE_MCP_SERVER = "use_mcp_server",
  DIFF_ERROR = "diff_error"
}
